# Generated by Django 4.2.3 on 2023-07-25 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=25)),
                ('pais', models.TextField()),
                ('edicionesDisputadas', models.IntegerField()),
                ('longitud', models.FloatField()),
                ('imagen', models.URLField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
