# Generated by Django 4.2.3 on 2023-07-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Circuito',
        ),
    ]
