# Generated by Django 4.2.3 on 2023-07-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_circuito_id_alter_circuito_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
