# Generated by Django 4.2.3 on 2023-08-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_voto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto',
            old_name='content_type',
            new_name='modelo_relacion',
        ),
    ]
