# Generated by Django 4.2.3 on 2023-08-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_content_type_voto_modelo_relacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto',
            old_name='modelo_relacion',
            new_name='content_type',
        ),
    ]
